# Feature Configuration File
# Set features to true or false to enable/disable them at "compile time"
# If MINIMAL_FEATURE is true, it will override and disable all optional features (Recording, Track, Search, Cycle, Info, Timer)

MINIMAL_FEATURE=false
RECORDING_FEATURE=false
TRACK_FEATURE=true
SEARCH_FEATURE=false
CYCLE_FEATURE=true
INFO_FEATURE=true
TIMER_FEATURE=true
