# This file is auto-generated by the configure step. Do not edit manually.

MINIMAL_FEATURE = True
RECORDING_FEATURE = False
TRACK_FEATURE = False
SEARCH_FEATURE = False
CYCLE_FEATURE = False
INFO_FEATURE = False
