# This file is auto-generated by the configure step. Do not edit manually.

MINIMAL_FEATURE = False
RECORDING_FEATURE = True
TRACK_FEATURE = True
SEARCH_FEATURE = True
CYCLE_FEATURE = True
INFO_FEATURE = True
TIMER_FEATURE = True
